---
# tasks file for webserver
- name: Install Apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: Install Git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: Clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/lucm9/tooling.git
    dest: /var/www/html
    force: yes

- name: Copy HTML content to one level up
  become: true
  ansible.builtin.command:
    cmd: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: Enable httpd to start after reboot
  become: true
  ansible.builtin.service:
    name: httpd
    enabled: yes

- name: Recursively remove /var/www/html/html/ directory
  become: true
  ansible.builtin.file:
    path: /var/www/html/html
    state: absent

# *************************************************************************
# - name: configure-tooling-website
#   import_tasks: "configure-tooling.yml"
- name: Configure tooling website
  become: true
  tasks:
    - name: configure-tooling-website
      import_tasks: "configure-tooling.yml"

    # Other tasks specific to your webserver configuration
