---
- name: install apache
  become: true
  yum:
    name: httpd
    state: present

- name: install git
  become: true
  yum:
    name: git
    state: present

- name: clone tooling repo
  become: true
  git:
    repo: https://github.com/lucm9/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  command: cp -r /var/www/html/html/ /var/www/

- name: start httpd service
  become: true
  service:
    name: httpd
    state: started

- name: recursively remove /var/www/html/html/ directory
  become: true
  file:
    path: /var/www/html/html
    state: absent

- name: disable default Apache site on Red Hat-based systems
  become: true
  block:
    - name: Stop httpd service
      command: systemctl stop httpd
      ignore_errors: yes

    - name: Disable httpd service
      command: systemctl disable httpd
      ignore_errors: yes

    - name: Check if welcome.conf exists
      stat:
        path: /etc/httpd/conf.d/welcome.conf
      register: welcome_conf_stat
      ignore_errors: True

    - name: Move welcome.conf if it exists
      command: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.disabled
      when: welcome_conf_stat.stat.exists
      ignore_errors: yes

    - name: Restart httpd service
      command: systemctl restart httpd
      ignore_errors: yes
  when: "'Red Hat' in ansible_distribution and ansible_distribution_major_version|int >= 7"
