---
# tasks file for webserver
- name: install apache
  become: true
  ansible.builtin.yum:
    name: "httpd"
    state: present

- name: install git
  become: true
  ansible.builtin.yum:
    name: "git"
    state: present

- name: clone a repo
  become: true
  ansible.builtin.git:
    repo: https://github.com/lucm9/tooling.git
    dest: /var/www/html
    force: yes

- name: copy html content to one level up
  become: true
  ansible.builtin.command:
    cmd: cp -r /var/www/html/html/ /var/www/

- name: Start service httpd, if not started
  become: true
  ansible.builtin.service:
    name: httpd
    state: started

- name: Enable httpd to start after reboot
  become: true
  ansible.builtin.service:
    name: httpd
    enabled: yes

- name: Move welcome.conf to backup
  become: true
  ansible.builtin.command:
    cmd: mv /etc/httpd/conf.d/welcome.conf /etc/httpd/conf.d/welcome.conf.back

- name: recursively remove /var/www/html/html/ directory
  become: true
  ansible.builtin.command:
    cmd: rm -rf /var/www/html/html

- name: Disable SELinux
  become: true
  tasks:
    - name: Disable SELinux for the current session
      ansible.builtin.seboolean:
        name: selinuxuser_tcp_server
        state: no
        persistent: yes

    - name: Set SELinux to permissive mode
      ansible.builtin.selinux:
        policy: targeted
        state: permissive
        persistent: yes

    - name: Disable SELinux in the configuration file
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
