---
- hosts: all
- name: Include dynamic variables 
  tasks:
  import_playbook: ../static-assignments/common.yml 
  include: ../dynamic-assignments/env-vars.yml
  tags:
    - always

- hosts: uat-webservers
- name: uat Webserver assignment
  import_playbook: ../static-assignments/uat-webservers.yml

- hosts: lb
- name : Install Mysql-DB
  import_playbook: ../static-assignments/database.yml
